[config]

[templates.niri]
input_path = "/home/lain/nix-config/dotfiles/niri/config.kdl.in"
output_path = "/home/lain/nix-config/dotfiles/niri/config.kdl"

[templates.fuzzel]
input_path = "/home/lain/nix-config/dotfiles/fuzzel/fuzzel.ini.in"
output_path = "/home/lain/nix-config/dotfiles/fuzzel/fuzzel.ini"

[templates.mako]
input_path = "/home/lain/nix-config/dotfiles/mako/config.in"
output_path = "/home/lain/nix-config/dotfiles/mako/config"

[templates.eww]
input_path = "/home/lain/nix-config/dotfiles/eww/eww.scss.in"
output_path = "/home/lain/nix-config/dotfiles/eww/eww.scss"

[templates.gtk]
input_path = "/home/lain/nix-config/dotfiles/gtk/gtk.css.in"
output_path = "/home/lain/nix-config/dotfiles/gtk/gtk.css"
