-- Generated by matugen from the current wallpaper. Do NOT edit this file;
-- edit matugen-colors.lua.in. Consumed by lua/theme.lua.
return {
  primary            = "#ffb2b9",
  on_primary         = "#561d26",
  primary_container  = "#72333b",
  secondary          = "#e5bdbf",
  tertiary           = "#e8c08e",
  error              = "#ffb4ab",
  on_surface         = "#f0dedf",
  on_surface_variant = "#d7c1c2",
  surface_variant    = "#524344",
  outline            = "#9f8c8d",
}
